#!/usr/bin/env python

import sys, os

from urllib import urlopen
import csv

gdocbase = "https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE"
#csvMC = list(csv.reader(urlopen(gdocbase + "/pub?gid=694776205&single=true&output=csv").readlines()))
csvMC = list(csv.reader(urlopen(gdocbase + "/pub?gid=212761185&single=true&output=csv").readlines()))

nameIdx = csvMC[0].index("Name")
titleIdx = csvMC[0].index("Title")
pathIdx = csvMC[0].index("Path")
xsecIdx = csvMC[0].index("Cross section (pb)")

ds=[]
for l in csvMC[1:]:
    if len(l) == 0 or len(l[0]) == 0: continue
    ds.append({'title':l[titleIdx],
               'name':l[nameIdx],
               'xsec':float(l[xsecIdx]),
               'path':l[pathIdx]})

#print ds
args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest"]
for aa in ds:
 if not (aa['name'].find("QCD")>-1 or aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1) :
   
   ddd = "python create-batch "
   ddd+= args[0]+" "+aa['name']+" "
   ddd+= args[1]+" filelist/"+aa['name']+"_0.txt "
   ddd+= args[2]+" 20 "
   if ( aa['name'].find("Double")>-1 or aa['name'].find("MuonEG")>-1 ) :
     ddd+= args[3]+" run_ntupleMakerRD_cfg.py "
   else :
     ddd+= args[3]+" run_ntupleMaker_cfg.py "
   #ddd+= args[4]+" /store/user/youngjo/Cattools/test" #+aa['name']

   print ddd
   os.system(ddd)





